buildFrameworks:
    name: Build Frameworks for Release
    agent:
        type: Unity::VM::osx
        image: desktop/unity-macos-10.15-xcode-12.2:stable
        flavor: m1.mac
    commands:
        - bash buildFrameworks.sh
    artifacts:
        build:
            paths:
                - "build/DeltaDNA-iOS.tar.gz"